name: stream_chat_flutter_example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  stream_chat_flutter:
    path: ../
  # stream_chat_localizations: ^8.0.0
  # stream_chat_persistence: ^8.0.0
  dart_jsonwebtoken: ^2.14.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  path_provider: ^2.1.4
  photo_manager: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/background_doodle.png
